FROM debian:@DEBIAN@-slim

ARG  PKG_COMMIT=@PKG_COMMIT@
ARG  VARNISH_VERSION=@VARNISH_VERSION@
ARG  DIST_SHA512=@DIST_SHA512@
ARG  VARNISH_MODULES_VERSION=@VARNISH_MODULES_VERSION@
ARG  VARNISH_MODULES_SHA512SUM=@VARNISH_MODULES_SHA512SUM@
ARG  VMOD_DYNAMIC_VERSION=@VMOD_DYNAMIC_VERSION@
ARG  VMOD_DYNAMIC_COMMIT=@VMOD_DYNAMIC_COMMIT@
ARG  VMOD_DYNAMIC_SHA512SUM=@VMOD_DYNAMIC_SHA512SUM@

ENV VARNISH_SIZE 100M

RUN set -e; \
    BASE_PKGS="curl dpkg-dev debhelper devscripts equivs git pkg-config apt-utils fakeroot sbuild"; \
    export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    mkdir -p /work/varnish /pkgs; \
    apt-get update; \
    apt-get install -y $BASE_PKGS; \
    # varnish
    cd /work/varnish; \
    git clone https://github.com/varnishcache/pkg-varnish-cache.git; \
    cd pkg-varnish-cache; \
    git checkout @PKG_COMMIT@; \
    rm -rf .git; \
    curl -f https://varnish-cache.org/downloads/varnish-@VARNISH_VERSION@.tgz -o $tmpdir/orig.tgz; \
    echo "@DIST_SHA512@  $tmpdir/orig.tgz" | sha512sum -c -; \
    tar xavf $tmpdir/orig.tgz --strip 1; \
    sed -i -e "s|@VERSION@|$VARNISH_VERSION|"  "debian/changelog"; \
    mk-build-deps --install --tool="apt-get -o Debug::pkgProblemResolver=yes --yes" debian/control; \
    sed -i '' debian/varnish*; \
    dpkg-buildpackage -us -uc -j"$(nproc)"; \
    apt-get -y install ../*.deb; \
    mv ../*dev*.deb /pkgs; \
    \
    # varnish-modules
    mkdir /work/varnish-modules; \
    cd /work/varnish-modules; \
    curl -fLo src.tar.gz https://github.com/varnish/varnish-modules/releases/download/$VARNISH_MODULES_VERSION/varnish-modules-$VARNISH_MODULES_VERSION.tar.gz; \
    echo "$VARNISH_MODULES_SHA512SUM  src.tar.gz" | sha512sum -c -; \
    tar xavf src.tar.gz --strip 1; \
    ./configure --libdir=/usr/lib; \
    make -j"$(nproc)" VERBOSE=1 install; \
    make -j"$(nproc)" VERBOSE=1 check; \
    \
    # vmod-dynamic
    mkdir /work/vmod-dynamic; \
    cd /work/vmod-dynamic; \
    curl -fLo src.tar.gz https://github.com/nigoroll/libvmod-dynamic/archive/$VMOD_DYNAMIC_COMMIT.tar.gz; \
    echo "$VMOD_DYNAMIC_SHA512SUM  src.tar.gz" | sha512sum -c -; \
    tar xavf src.tar.gz --strip 1; \
    # patching things up for armv8
    cp /work/varnish/pkg-varnish-cache/include/vmb.h src/vmb.h; \
    sed -i '14 a AC_CHECK_HEADERS([stdatomic.h])' configure.ac; \
    # actual build
    ./autogen.sh; \
    ./configure --libdir=/usr/lib; \
    make -j"$(nproc)" VERBOSE=1 install; \
    make -j"$(nproc)" VERBOSE=1 check; \
    # clean up
    apt-get -y purge --auto-remove varnish-build-deps $BASE_PKGS; \
    rm -rf /var/lib/apt/lists/* /work/ /usr/lib/varnish/vmods/libvmod_*.la; \
    chown varnish /var/lib/varnish;

WORKDIR /etc/varnish

COPY scripts/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/docker-varnish-entrypoint"]

USER varnish
EXPOSE 80 8443
CMD []
