language: bash
services: docker

env:
  - NAME=6.3 WORKDIR=fresh/debian
  - NAME=6.0 WORKDIR=stable/debian
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${WORKDIR}"
  - image="varnish:${NAME}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
