#!/usr/bin/env bash
set -euo pipefail

UPSTREAM="docker-library/official-images"
LIBRARY_PATH_IN_REPO="library/varnish"
FORK="varnish/official-images"   # default; override with -f OWNER/REPO
LIBRARY_FILE="library.varnish"   # default; override with -l PATH

while getopts "f:l:" opt; do
	case "$opt" in
		f) FORK="$OPTARG" ;;
		l) LIBRARY_FILE="$OPTARG" ;;
		*) echo "usage: $0 [-f fork-owner/repo] [-l library-file]" >&2; exit 1 ;;
	esac
done
FORK_OWNER="${FORK%%/*}"
LOCAL_LIBRARY_FILE="$(realpath "$LIBRARY_FILE")"

: "${GH_TOKEN:?GH_TOKEN (a token with write access to $FORK) must be set}"

SRC_COMMIT="$(git rev-parse --short HEAD)"
BRANCH="library-update"

gh repo view "$FORK" >/dev/null 2>&1 || {
	echo "Fork $FORK not found. Fork docker-library/official-images to $FORK_OWNER first (one-time, manual), see MAINTENANCE.md." >&2
	exit 1
}

gh repo sync "$FORK" --source "$UPSTREAM" --branch master --force

EXISTING_PR="$(gh pr list --repo "$UPSTREAM" \
	--head "${FORK_OWNER}:${BRANCH}" --state open \
	--json number --jq '.[0].number // empty')"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT
gh repo clone "$FORK" "$WORKDIR" -- --depth=1 --branch master --single-branch --quiet
cd "$WORKDIR"
git config user.email "varnish-bot@users.noreply.github.com"
git config user.name "Varnish Release Bot"

git switch -C "$BRANCH" origin/master
cp "$LOCAL_LIBRARY_FILE" "$LIBRARY_PATH_IN_REPO"

if git diff --quiet -- "$LIBRARY_PATH_IN_REPO"; then
	echo "No change vs upstream master for commit $SRC_COMMIT; nothing to do."
	exit 0
fi

git add "$LIBRARY_PATH_IN_REPO"
git commit -m "varnish: update library/varnish (docker-varnish@${SRC_COMMIT})"
git push --force origin "$BRANCH"

if [ -n "$EXISTING_PR" ]; then
	echo "Updated existing PR #$EXISTING_PR for branch $BRANCH."
	exit 0
fi

gh pr create --repo "$UPSTREAM" \
	--title "varnish: update library/varnish (${SRC_COMMIT})" \
	--body "Automated PR from varnish/docker-varnish@${SRC_COMMIT}, generated by populate.sh + open-library-pr.sh." \
	--base master \
	--head "${FORK_OWNER}:${BRANCH}"
