FROM alpine:3.15

ARG  PKG_COMMIT=@PKG_COMMIT@
ARG  VARNISH_VERSION=@VARNISH_VERSION@
ARG  DIST_SHA512=@DIST_SHA512@
ARG  VARNISH_MODULES_VERSION=@VARNISH_MODULES_VERSION@
ARG  VARNISH_MODULES_SHA512SUM=@VARNISH_MODULES_SHA512SUM@
ARG  VMOD_DYNAMIC_VERSION=@VMOD_DYNAMIC_VERSION@
ARG  VMOD_DYNAMIC_COMMIT=@VMOD_DYNAMIC_COMMIT@
ARG  VMOD_DYNAMIC_SHA512SUM=@VMOD_DYNAMIC_SHA512SUM@

ENV VARNISH_SIZE 100M

RUN set -e;\
    BASE_PKGS="tar alpine-sdk sudo py3-docutils python3 autoconf automake libtool"; \
    apk add --virtual varnish-build-deps -q --no-progress --update $BASE_PKGS; \
    adduser -D builder; \
    echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder; \
    addgroup builder abuild; \
    su builder -c "abuild-keygen -nai"; \
    \
    # varnish tarball and packaging
    git clone https://github.com/varnishcache/pkg-varnish-cache.git; \
    cd pkg-varnish-cache/alpine; \
    git checkout $PKG_COMMIT; \
    sed -i APKBUILD \
        -e "s/pkgver=@VERSION@/pkgver=$VARNISH_VERSION/" \
	-e 's@^source=.*@source="http://varnish-cache.org/_downloads/varnish-$pkgver.tgz"@' \
	-e "s/^sha512sums=.*/sha512sums=\"$DIST_SHA512  varnish-\$pkgver.tgz\"/"; \
    \
    # build and install varnish package
    chown builder -R .; \
    su builder -c "abuild -r"; \
    apk add --allow-untrusted ~builder/packages/pkg-varnish-cache/*/*.apk; \
    echo -e 'vcl 4.1;\nbackend default none;' > /etc/varnish/default.vcl; \
     \
    # varnish-modules
    mkdir -p /work/varnish-modules; \
    cd /work/varnish-modules; \
    curl -fLo src.tar.gz https://github.com/varnish/varnish-modules/releases/download/$VARNISH_MODULES_VERSION/varnish-modules-$VARNISH_MODULES_VERSION.tar.gz; \
    echo "$VARNISH_MODULES_SHA512SUM  src.tar.gz" | sha512sum -c -; \
    tar xavf src.tar.gz --strip 1; \
    ./configure --libdir=/usr/lib; \
    make -j"$(nproc)" VERBOSE=1 install; \
    make -j"$(nproc)" VERBOSE=1 check; \
    \
    # vmod-dynamic
    mkdir /work/vmod-dynamic; \
    cd /work/vmod-dynamic; \
    curl -fLo src.tar.gz https://github.com/nigoroll/libvmod-dynamic/archive/$VMOD_DYNAMIC_COMMIT.tar.gz; \
    echo "$VMOD_DYNAMIC_SHA512SUM  src.tar.gz" | sha512sum -c -; \
    tar xavf src.tar.gz --strip 1; \
    # patching things up for armv8
    sed -i '14 a AC_CHECK_HEADERS([stdatomic.h])' configure.ac; \
    git clone https://github.com/varnishcache/varnish-cache.git; \
    cd varnish-cache; \
    git checkout d48636d23bb277ca8650a6174c872d74080f2859; \
    cp include/vmb.h ../src/vmb.h; \
    cd /work/vmod-dynamic; \
    # actual build
    ./autogen.sh; \
    ./configure --libdir=/usr/lib; \
    make -j"$(nproc)" VERBOSE=1 install; \
    make -j"$(nproc)" VERBOSE=1 check; \
    \
    # cleanup
    apk del --no-network varnish-build-deps; \
    rm -rf ~builder /pkg-varnish-cache /varnish-modules /vmod-dynamic /etc/sudoers.d/builder; \
    deluser --remove-home builder; \
    chown varnish /var/lib/varnish;

WORKDIR /etc/varnish

COPY scripts/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/docker-varnish-entrypoint"]

USER varnish
EXPOSE 80 8443
CMD []
