name: Publish docker-library/official-images library PR

on:
  workflow_dispatch:

jobs:
  publish-library-pr:
    runs-on: ubuntu-latest
    if: github.repository == 'varnish/docker-varnish'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate library file
        run: ./populate.sh library
      - name: Mint GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.VARNISH_OFFICIAL_IMAGES_PUBLISHER_APPID }}
          private-key: ${{ secrets.VARNISH_OFFICIAL_IMAGES_PUBLISHER_KEY }}
          owner: varnish
          repositories: official-images
      - name: Open/update PR against docker-library/official-images
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: ./open-library-pr.sh
