name: GitHub CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  vmods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build varnish:latest
        run: docker build -t varnish fresh/debian/
      - name: Build vmod images
        run: cd vmod-examples; ./examples.sh
